# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' GLambda (Description)
#'
#' This function calculates genomic constant lambda from observed
#' p values. Values are calcuated as median of p-values' chi-test
#' statistic, divided by 0.4549364. This result indicate deflation
#' (< 1) or inflation (> 1) of the GWAS p values. If pvalues are
#' extremely inflated, then adjustments to model are necessary.
#' @title GLambda
#' @param x A numeric vector of P values
#' @return numeric value
#' @author Franjo, Mingjing, and Xiaoxiao
#' @examples
#' GLambda(ADHDMetaP$P)
#' @export
GLambda <- function(x) {
    .Call('_GWASr_GLambda', PACKAGE = 'GWASr', x)
}

